#!/bin/bash 
# Run the frstack.yml playbook
# Any optional args are tags to pass to the ansible-playbook command (comma delimited)
# TODO: Make this work across all environments 
#     
# See http://docs.ansible.com/intro_getting_started.html#host-key-checking
export ANSIBLE_HOST_KEY_CHECKING=False

SCRIPTPATH="$(cd "$(dirname "$0")"; pwd -P)"

# Uncomment to debug
DEBUG=-vvvv

# Uncomment the correct env var here for your target

# Default inventory is for vagrant

INVENTORY=$SCRIPTPATH/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory

export ANSIBLE_HOSTS=$INVENTORY

TAGS=""

if [ $# -gt 0 ]
then 
	TAGS="--tags $1"
fi

PRIVATE_KEY="$SCRIPTPATH/.vagrant/machines/oisserver/virtualbox/private_key"
# Run the frstack playbook 
cd ../ansible
#ansible-playbook $DEBUG --user=vagrant --private-key=~/.vagrant.d/insecure_private_key -i $INVENTORY frstack.yml

#ansible-playbook $DEBUG --user=vagrant --private-key=./.vagrant/machines/oisserver/virtualbox/private_key -i $INVENTORY frstack.yml $TAGS

ansible-playbook $DEBUG --user=vagrant --private-key $PRIVATE_KEY -i $INVENTORY frstack.yml $TAGS
