#!/bin/bash 
# Run the frstack.yml playbook
# Any first optioanl arg is assumted to be tags to pass to the ansible-playbook command (comma delimited)
# TODO: Make this work across all environments 
#     
# See http://docs.ansible.com/intro_getting_started.html#host-key-checking
export ANSIBLE_HOST_KEY_CHECKING=False

# Uncomment to debug
#DEBUG=-vvvv

SCRIPTPATH="$(cd "$(dirname "$0")"; pwd -P)"

# Uncomment the correct env var here for your target


# Set the ec2 inventory
INVENTORY=$SCRIPTPATH/ec2.py  

#export ANSIBLE_HOSTS=$INVENTORY

#USER=$LOGNAME
USER=centos

TAGS=""

if [ $# -gt 0 ]
then 
	TAGS="--tags $1"
fi


KEYPAIR=~/etc/frstack-demo.pem

# Run the frstack playbook 

cd ../ansible
#ansible-playbook $DEBUG -i $INVENTORY  --private-key ~/.ssh/google_compute_engine --user=$USER frstack.yml $TAGS
ansible-playbook $DEBUG -i $SCRIPTPATH/hosts  --private-key $KEYPAIR --user=$USER frstack.yml $TAGS

