#!/bin/bash 
# Run the frstack.yml playbook
# Any first optioanl arg is assumted to be tags to pass to the ansible-playbook command (comma delimited)
# TODO: Make this work across all environments 
#     
# See http://docs.ansible.com/intro_getting_started.html#host-key-checking
export ANSIBLE_HOST_KEY_CHECKING=False

# Uncomment to debug
DEBUG=-vvvv

TAGS=""

if [ $# -gt 0 ]
then 
	TAGS="--tags $1"
fi

# Run the frstack playbook 
ansible-playbook $DEBUG frstack.yml $TAGS

